server:
  port: 1111
  ssl:    enabled: true
    client-auth: need
    key-store: classpath:server.jks
    key-store-password: password
    key-alias: server
    key-store-type: JKS
    key-store-provider: SUN
    trust-store: classpath:server.jks
    trust-store-password: password
    trust-store-type: JKS